### ISSUE TITLE
[Feature] Convert page to Angular

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/chan4077.github.io#37]
# TODO
- [x] Redesign page for Angular Material
- [ ] Add Angular Router
- [x] Add project pages
- [ ] Add blog? (potentially)
- [ ] Add PWA support
- [ ] Dynamic title

**Comment by himharsh1997** [comment]
I would like to help.

**Comment by Chan4077** [comment]
@himharsh1997 Go ahead! I'm looking for help from others if possible.

To get started, fork this repository by clicking on the "Fork" button next to the "Star" button on the top right of the page.
Then, add your code there and send a pull request by comparing the changes.

[More info](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by Chan4077** [comment]
I've been working on this for a while. It's been reworked from the ground up and has cool animations and everything.

Here are some screenshots as of now:

About page:

![About page](https://user-images.githubusercontent.com/20047125/43144343-78123712-8f8f-11e8-947c-956c01b44358.jpg)

Sidenav:

![Sidenav](https://user-images.githubusercontent.com/20047125/43144379-93988860-8f8f-11e8-8a1f-b6c6b68aae45.jpg)

Home page:

![Home page](https://user-images.githubusercontent.com/20047125/43144405-a3d0749a-8f8f-11e8-957e-27a798c42e6b.jpg)

`ngx-ytd-api` page:

![screenshot 2018-07-24 at 22 18 52](https://user-images.githubusercontent.com/20047125/43144412-aa4656b4-8f8f-11e8-98c7-7993634f5967.jpg)

**Comment by Chan4077** [comment]
I'll close this issue as I'm using [Material Components for the web](https://github.com/material-components/material-components-web).
